#!/usr/bin/env bash

is_in_workspace() {
  local app_name="${1-}"
  local -i ws_number
  ws_number=$(swaymsg -t get_tree | jq -r \
    ". .nodes[].nodes[] | {id, type, name, nodes: (.nodes[].nodes[] | select(.window_properties.class == \"$app_name\") // empty)} | .name") || 0
  [ "$ws_number" -gt 0 ] && return
  false
}

get_ws_number() {
  local app_name="${1-}"
  local -i ws_number
  ws_number=$(swaymsg -t get_tree | jq -r \
    ". .nodes[].nodes[] | {id, type, name, nodes: (.nodes[].nodes[] | select(.window_properties.class == \"$app_name\") // empty)} | .name") || 0
  echo "$ws_number"
}

get_focused_ws() {
  local -i ws_number
  ws_number=$(swaymsg -t get_workspaces | jq '.[] | select(.focused==true) | .num')
  echo "$ws_number"
}
