#!/usr/bin/env bash

# Amazing Fuzzy finder
if hash fzf 2> /dev/null; then
  fzf_keymaps=(
    ctrl-d:half-page-down
    ctrl-u:half-page-up
    ctrl-b:preview-down
    ctrl-n:preview-up
    ctrl-h:preview-half-page-down
    ctrl-l:preview-half-page-up
    ctrl-t:toggle-preview-wrap
    ctrl-space:toggle+down
    tab:toggle+down
  )
  keymaps="$(printf ",%s" "${fzf_keymaps[@]}")"

  export FZF_DEFAULT_OPTS="
    --layout=reverse --margin=1 --info=inline-right --separator=- --no-height
    --bind ${keymaps:1}
    --bind 'ctrl-y:execute-silent(realpath {} | wl-copy)'
    --color=fg:7,fg+:3
    --color=bg:#1e222a,bg+:#1e222a
    --color=hl:4,hl+:11
    --color=info:14,marker:6
    --color=prompt:9,spinner:5
    --color=pointer:9,header:2
    --color=border:#1e222a,list-border:8
    --color=label:3,query:7
    --color=preview-border:8,preview-scrollbar:#1e222a
    --border=rounded
    --border-label=''
    --preview-window=border-rounded
    --prompt='> '
    --marker='+'
    --pointer='>>'
    --separator='─'
    --scrollbar='│'"

  # shellcheck disable=2016
  opener='
    case "$(file --dereference --mime-type {} -b)" in
      inode/x-empty)     footclient $EDITOR {} &> /dev/null & ;;
      text/*)            footclient $EDITOR {} &> /dev/null & ;;
      audio/midi)        footclient $EDITOR {} &> /dev/null & ;;
      audio/*)           nohup mpv {} &> /dev/null & ;;
      video/*)           nohup mpv {} &> /dev/null & ;;
      application/epub*) footclient /usr/bin/epy {} &> /dev/null & ;;
      application/pdf)   nohup zathura {} &> /dev/null & ;;
      *)                 footclient $EDITOR {} &> /dev/null & ;;
    esac'

  export FZF_CTRL_T_OPTS="
    --walker-skip .git,node_modules,target
    --preview '$XDG_CONFIG_HOME/lf/preview {}'
    --bind 'enter:execute-silent($opener)'"

  export FZF_ALT_C_OPTS="
    --walker-skip .git,node_modules,target
    --preview 'tree -s -h --du -C {}'"

  if hash yt 2> /dev/null; then
    export YT_X_FZF_OPTS=$FZF_DEFAULT_OPTS
  fi

  if hash rg 2> /dev/null; then
    export FZF_DEFAULT_COMMAND="
      rg --vimgrep --files --follow --hidden --no-ignore-vcs --smart-case --glob !**/.git/*"

    export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND
  fi

  unset fzf_keymaps keymaps opener
  eval "$(fzf --bash)"
fi
