# autostart background applications
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# autostarts
exec {
    $initialize_foot_server
    $initialize_mako_service
    $initialize_mounting_service
    $initialize_poweralert_service
    # $initialize_swayidle_service
    # $initialize_idlehack_service
    # $initialize_swayr_service

    $start_xdg-dirs
    $start_autotiling
    # $swayidle
    # $start_dex

    # clears empty crypts dirs
    $clear_crypts

    # toggles border on floating windows
    $floating_borders_toggle

    # set focus to HDMI-A-1 on start
    $swaymonitors --focus WIDE

    # mutes audio on start
    $volume_mute_init
    $mic_mute_init
}

# commands that "reload" something
exec_always {
    $kill_waybar
    $swaymonitors --profile
    $start_xdg_keyboard
    $start_noisetorch
    $swappy_notify_daemon
    $calendar_daemon
}
